DX-208 <update automerge>
urbansportsclub/usc-reusable-workflows pull request #107
Opened 2024-04-22 13:52 UTC by NamanNacedo

2024-04-22 13:58 UTC, onurguzel commented on .github/workflows/automerge-dependabot.yml
> +        if gh pr checks "$PR_URL" --json conclusion | grep -q '"conclusion": "FAILURE"'; then
This line should be enough:
```shell
gh pr checks $PR_URL --required  --required --watch --fail-fast > /dev/null
```

- `--required` filters the required checks only
- `--watch` wait for checks to finish executing
- `--fail-fast` exits without waiting for other checks if one already failed

2024-04-22 14:34 UTC, GersonTrj requested changes

2024-04-22 14:34 UTC, GersonTrj commented on .github/workflows/automerge-dependabot-with-codeowners.yml
> +      if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}
don't you need to add ["needs"](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds) so the automerge step depends on the check?

2024-04-23 10:05 UTC, GersonTrj commented on .github/workflows/automerge-dependabot-with-codeowners.yml
> +      if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}
yeah, I got confused, I though it was a different job. I already checked it with Christophe so all good.

2024-04-23 10:05 UTC, GersonTrj approved these changes

2024-04-23 11:58 UTC, merged